REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;

INSERT INTO public.categories (name, slug, description, image, product_count, featured, sort_order) VALUES
('Sculptural Baskets','sculpture','Wild-fringed statement forms woven as living sculpture.','/__l5e/assets-v1/c9b30099-29a0-4b71-864e-c7f30d51aae5/bolga-hero.jpg',3,true,1),
('Lampshades','lampshade','Hand-coiled pendant shades that filter light into pattern.','/__l5e/assets-v1/4d820abd-023e-46e1-b068-2d5ba0f1ed77/product-lampshade.jpg',2,true,2),
('Woven Fans','fans','Leather-trimmed hand fans in natural dye palettes.','/__l5e/assets-v1/79683c8d-0da3-4ebf-88bd-cea7436f1f02/product-fan.jpg',2,true,3),
('Storage Baskets','storage','Deep, sturdy baskets for blankets, firewood and market days.','/__l5e/assets-v1/f9dcf4cf-248f-49c2-87cd-ea4e34f43ff8/product-storage.jpg',3,true,4),
('Planters','planter','Grass planters that soften architectural greenery.','/__l5e/assets-v1/65112f8b-4362-4647-8eb7-bed67bf77406/planter.jpg',2,false,5),
('Market Totes','tote','Leather-handled shoppers built for a lifetime of errands.','/__l5e/assets-v1/80686690-31c5-4272-b939-6b9c46601886/tote.jpg',1,true,6),
('Pet Beds','pet-bed','Round woven nests with washable cushions.','/__l5e/assets-v1/f1e7e7d6-a0fb-4a9a-a86b-af6c069e390c/petbed.jpg',1,false,7);

INSERT INTO public.products (name, slug, sku, category, price, sale_price, stock_quantity, low_stock_threshold, status, featured, primary_image, images, description, dimensions, artisan_story, care_instructions, color, tags, rating, review_count, weight_kg, capacity, handle) VALUES
('Zebra Fringe Sculpture Basket','zebra-fringe-sculpture-basket','VS-SCU-001','sculpture',245,198,4,3,'active',true,'/__l5e/assets-v1/c9b30099-29a0-4b71-864e-c7f30d51aae5/bolga-hero.jpg',ARRAY['/__l5e/assets-v1/c9b30099-29a0-4b71-864e-c7f30d51aae5/bolga-hero.jpg','/__l5e/assets-v1/a81bddfd-e0c5-4410-b161-26cb04573b5a/product-sculpture.jpg'],'A monumental collector piece: charcoal and natural straw stripes rise into an untrimmed fringe crown, each strand left wild by the weaver as a signature.','48cm H x 52cm W','Woven over eleven days by Ayamga Atinga of the Sumbrungu cooperative, who learned the wild-fringe finish from her grandmother.','Mist lightly with warm water and reshape by hand. Keep out of direct sun.',ARRAY['Charcoal','Natural Straw'],ARRAY['statement','collector','fringe'],4.9,3,1.80,'Decorative','None'),
('Sahel Vase Sculpture','sahel-vase-sculpture','VS-SCU-002','sculpture',210,NULL,6,3,'active',true,'/__l5e/assets-v1/a81bddfd-e0c5-4410-b161-26cb04573b5a/product-sculpture.jpg',ARRAY['/__l5e/assets-v1/a81bddfd-e0c5-4410-b161-26cb04573b5a/product-sculpture.jpg','/__l5e/assets-v1/c9b30099-29a0-4b71-864e-c7f30d51aae5/bolga-hero.jpg'],'An hourglass silhouette in banded charcoal, finished with a soft grass plume that catches afternoon light.','44cm H x 34cm W','Shaped on the knee without a mould — the waist is judged entirely by eye.',ARRAY['Mist with warm water, reshape, air dry away from heat.']::text[][1],ARRAY['Charcoal','Natural Straw'],ARRAY['sculpture','plume'],4.8,1,1.40,'Decorative','None'),
('Dusk Plume Vessel','dusk-plume-vessel','VS-SCU-003','sculpture',165,139,2,3,'active',false,'/__l5e/assets-v1/a81bddfd-e0c5-4410-b161-26cb04573b5a/product-sculpture.jpg',ARRAY['/__l5e/assets-v1/a81bddfd-e0c5-4410-b161-26cb04573b5a/product-sculpture.jpg'],'A smaller sculptural vessel for console tables and shelves, with a low charcoal band and open plume.','32cm H x 26cm W','Woven by the youngest weavers of the cooperative as their mastery piece.','Spray, reshape, dry naturally.',ARRAY['Natural Straw','Charcoal'],ARRAY['sale','small-space'],4.6,0,0.90,'Decorative','None'),
('Savannah Pendant Lampshade','savannah-pendant-lampshade','VS-LMP-001','lampshade',185,NULL,9,3,'active',true,'/__l5e/assets-v1/4d820abd-023e-46e1-b068-2d5ba0f1ed77/product-lampshade.jpg',ARRAY['/__l5e/assets-v1/4d820abd-023e-46e1-b068-2d5ba0f1ed77/product-lampshade.jpg'],'A bell-form pendant in ochre, terracotta and charcoal bands that throws warm woven shadow across a room.','40cm H x 36cm dia','Dyed with roots and bark gathered at the end of the dry season.','Dust with a dry brush. Use LED bulbs only.',ARRAY['Ochre','Terracotta','Natural Straw'],ARRAY['lighting','bestseller'],4.9,2,1.10,'E27 fitting','Cord mount'),
('Harmattan Dome Shade','harmattan-dome-shade','VS-LMP-002','lampshade',149,119,5,3,'active',false,'/__l5e/assets-v1/4d820abd-023e-46e1-b068-2d5ba0f1ed77/product-lampshade.jpg',ARRAY['/__l5e/assets-v1/4d820abd-023e-46e1-b068-2d5ba0f1ed77/product-lampshade.jpg'],'A wide, shallow dome in natural straw with a single indigo band — ideal above a dining table.','26cm H x 45cm dia','Coiled flat then lifted into shape over a clay former.','Dust with a dry brush. Use LED bulbs only.',ARRAY['Natural Straw','Indigo'],ARRAY['lighting','sale'],4.7,0,0.95,'E27 fitting','Cord mount'),
('Terracotta Sunburst Fan','terracotta-sunburst-fan','VS-FAN-001','fans',68,NULL,18,4,'active',true,'/__l5e/assets-v1/79683c8d-0da3-4ebf-88bd-cea7436f1f02/product-fan.jpg',ARRAY['/__l5e/assets-v1/79683c8d-0da3-4ebf-88bd-cea7436f1f02/product-fan.jpg'],'A hand fan with a radiating terracotta sunburst, bound in vegetable-tanned leather and finished with a looped handle.','42cm H x 38cm W','Trimmed by leather workers in Bolgatanga market, a craft passed down father to son.','Wipe leather with a dry cloth. Mist grass to refresh.',ARRAY['Terracotta','Natural Straw'],ARRAY['fan','leather','gift'],4.8,1,0.30,'Wall or hand','Wrapped leather'),
('Indigo Ray Fan','indigo-ray-fan','VS-FAN-002','fans',58,46,12,4,'active',false,'/__l5e/assets-v1/79683c8d-0da3-4ebf-88bd-cea7436f1f02/product-fan.jpg',ARRAY['/__l5e/assets-v1/79683c8d-0da3-4ebf-88bd-cea7436f1f02/product-fan.jpg'],'Indigo rays over pale straw, leather bound. Beautiful in a gallery wall of three.','40cm H x 36cm W','Indigo vats are shared between families and topped up for generations.','Wipe leather with a dry cloth. Mist grass to refresh.',ARRAY['Indigo','Natural Straw'],ARRAY['fan','sale'],4.5,0,0.28,'Wall or hand','Wrapped leather'),
('Midnight Stripe Storage Basket','midnight-stripe-storage-basket','VS-STO-001','storage',158,NULL,11,3,'active',true,'/__l5e/assets-v1/f9dcf4cf-248f-49c2-87cd-ea4e34f43ff8/product-storage.jpg',ARRAY['/__l5e/assets-v1/f9dcf4cf-248f-49c2-87cd-ea4e34f43ff8/product-storage.jpg'],'A deep U-shopper in indigo and straw stripes with double leather handles — blankets, firewood, laundry, market hauls.','38cm H x 46cm W','Handles are stitched with waxed thread so they carry 15kg without stretching.','Mist and reshape if folded in transit. Spot clean only.',ARRAY['Indigo','Natural Straw'],ARRAY['storage','bestseller','leather'],4.9,2,1.60,'45 litres','Double leather'),
('Forest Band Storage Basket','forest-band-storage-basket','VS-STO-002','storage',142,NULL,7,3,'active',false,'/__l5e/assets-v1/f9dcf4cf-248f-49c2-87cd-ea4e34f43ff8/product-storage.jpg',ARRAY['/__l5e/assets-v1/f9dcf4cf-248f-49c2-87cd-ea4e34f43ff8/product-storage.jpg'],'A calm forest-green band across natural straw, with a rolled rim that holds its shape.','36cm H x 42cm W','Green dye is built up over three dips to reach this depth.','Mist and reshape. Keep dry.',ARRAY['Forest','Natural Straw'],ARRAY['storage'],4.6,0,1.50,'38 litres','Double leather'),
('Ochre Nesting Pair','ochre-nesting-pair','VS-STO-003','storage',196,168,3,3,'active',true,'/__l5e/assets-v1/f9dcf4cf-248f-49c2-87cd-ea4e34f43ff8/product-storage.jpg',ARRAY['/__l5e/assets-v1/f9dcf4cf-248f-49c2-87cd-ea4e34f43ff8/product-storage.jpg','/__l5e/assets-v1/65112f8b-4362-4647-8eb7-bed67bf77406/planter.jpg'],'Two baskets that nest together, in ochre and straw. Sold as a pair.','40cm and 32cm H','A pair is woven by two sisters working side by side.','Mist and reshape. Keep dry.',ARRAY['Ochre','Natural Straw'],ARRAY['storage','set','sale'],4.8,0,2.60,'50 and 30 litres','Double leather'),
('Sage Band Grass Planter','sage-band-grass-planter','VS-PLA-001','planter',124,NULL,8,3,'active',true,'/__l5e/assets-v1/65112f8b-4362-4647-8eb7-bed67bf77406/planter.jpg',ARRAY['/__l5e/assets-v1/65112f8b-4362-4647-8eb7-bed67bf77406/planter.jpg'],'A straight-sided planter with a deep sage band, sized for a mature fiddle leaf or bird of paradise.','42cm H x 38cm dia','Woven tightly enough to hold a liner without sagging.','Use a plastic liner. Never water through the grass.',ARRAY['Forest','Natural Straw'],ARRAY['planter','interior'],4.7,1,1.20,'Fits 30cm pot','None'),
('Straw Column Planter','straw-column-planter','VS-PLA-002','planter',98,79,6,3,'active',false,'/__l5e/assets-v1/65112f8b-4362-4647-8eb7-bed67bf77406/planter.jpg',ARRAY['/__l5e/assets-v1/65112f8b-4362-4647-8eb7-bed67bf77406/planter.jpg'],'An undyed column planter, all natural straw, for a quieter corner.','36cm H x 30cm dia','Undyed grass shows the true colour of the harvest.','Use a plastic liner. Never water through the grass.',ARRAY['Natural Straw'],ARRAY['planter','sale'],4.4,0,1.00,'Fits 24cm pot','None'),
('Golden Check Market Tote','golden-check-market-tote','VS-TOT-001','tote',132,NULL,14,4,'active',true,'/__l5e/assets-v1/80686690-31c5-4272-b939-6b9c46601886/tote.jpg',ARRAY['/__l5e/assets-v1/80686690-31c5-4272-b939-6b9c46601886/tote.jpg'],'A golden ochre check shopper with tall rolled leather handles that soften with use.','34cm H x 40cm W','Checks are counted, never drawn — the weaver keeps the grid in her head.','Mist and reshape. Condition leather twice a year.',ARRAY['Ochre','Natural Straw'],ARRAY['tote','leather','bestseller'],4.9,1,0.85,'28 litres','Rolled leather'),
('Charcoal Stripe Pet Nest','charcoal-stripe-pet-nest','VS-PET-001','pet-bed',118,NULL,5,3,'active',false,'/__l5e/assets-v1/f1e7e7d6-a0fb-4a9a-a86b-af6c069e390c/petbed.jpg',ARRAY['/__l5e/assets-v1/f1e7e7d6-a0fb-4a9a-a86b-af6c069e390c/petbed.jpg'],'A low round nest in charcoal stripes with a washable cotton cushion. Cats claim it within the hour.','18cm H x 60cm dia','Woven with a doubled base so it survives enthusiastic kneading.','Cushion machine washable at 30C. Mist the grass to reshape.',ARRAY['Charcoal','Natural Straw'],ARRAY['pet','cushion'],4.8,0,1.30,'Up to 8kg pet','None'),
('Harvest Fringe Study','harvest-fringe-study','VS-SCU-004','sculpture',275,NULL,2,3,'draft',false,'/__l5e/assets-v1/a81bddfd-e0c5-4410-b161-26cb04573b5a/product-sculpture.jpg',ARRAY['/__l5e/assets-v1/a81bddfd-e0c5-4410-b161-26cb04573b5a/product-sculpture.jpg'],'An unreleased study piece from the 2026 harvest collection.','52cm H x 50cm W','Prototype woven during the studio residency.','Mist and reshape.',ARRAY['Charcoal','Natural Straw'],ARRAY['archive'],0,0,1.90,'Decorative','None');

INSERT INTO public.reviews (product_id, customer_name, rating, title, comment, is_approved, is_featured, is_verified_purchase, created_at)
SELECT p.id, v.customer_name, v.rating, v.title, v.comment, true, v.featured, true, now() - (v.days || ' days')::interval
FROM (VALUES
 ('zebra-fringe-sculpture-basket','Marguerite L.',5,'A living sculpture','It arrived folded, I misted it, and within an hour it opened into the most extraordinary object in my house.',true,6),
 ('zebra-fringe-sculpture-basket','Tomas R.',5,'Worth every cedi','The fringe is wilder than the photos. Exactly what I hoped for.',false,19),
 ('zebra-fringe-sculpture-basket','Ama D.',4,'Beautiful, slightly smaller','Gorgeous weave. Read the dimensions carefully — mine sits on a plinth.',false,31),
 ('sahel-vase-sculpture','Nils P.',5,'The waist is unreal','Hard to believe this was shaped by eye alone.',true,11),
 ('savannah-pendant-lampshade','Ingrid S.',5,'Warm woven shadows','At night the pattern spills across the ceiling. Total transformation.',true,8),
 ('savannah-pendant-lampshade','Kofi A.',5,'Excellent craft','Second one I have bought. Packed beautifully.',false,24),
 ('midnight-stripe-storage-basket','Rachel V.',5,'Handles are serious','Carried firewood all winter, still perfect.',true,14),
 ('midnight-stripe-storage-basket','Jean-Luc M.',5,'Everyday luxury','Deep, sturdy, quietly beautiful.',false,27),
 ('terracotta-sunburst-fan','Selina O.',5,'Framed it instead','Too pretty to fan with. It hangs in the hallway.',true,5),
 ('sage-band-grass-planter','Owen T.',5,'Perfect green','The sage band is exactly the tone I wanted.',false,17),
 ('golden-check-market-tote','Priya N.',5,'My saturday bag','The leather has already softened. Holds an absurd amount.',true,9)
) AS v(slug, customer_name, rating, title, comment, featured, days)
JOIN public.products p ON p.slug = v.slug;

INSERT INTO public.orders (order_number, customer, items, subtotal, shipping_cost, tax, total, payment_method, payment_status, fulfillment_status, tracking_number, tracking_carrier, currency, created_at) VALUES
('VS-24081','{"name":"Ingrid Solberg","email":"ingrid@example.com","phone":"+47 900 11 222","address":"Bygdoy alle 14","city":"Oslo","postalCode":"0262","country":"Norway"}','[{"productId":"","name":"Savannah Pendant Lampshade","price":185,"quantity":1,"image":"/__l5e/assets-v1/4d820abd-023e-46e1-b068-2d5ba0f1ed77/product-lampshade.jpg"}]',185,0,9.25,194.25,'card','paid','delivered','DHL8841203','DHL Express','USD',now() - interval '21 days'),
('VS-24082','{"name":"Rachel Vandenberg","email":"rachel@example.com","phone":"+31 6 1234 5678","address":"Prinsengracht 401","city":"Amsterdam","postalCode":"1016 HL","country":"Netherlands"}','[{"productId":"","name":"Midnight Stripe Storage Basket","price":158,"quantity":2,"image":"/__l5e/assets-v1/f9dcf4cf-248f-49c2-87cd-ea4e34f43ff8/product-storage.jpg"}]',316,0,15.80,331.80,'card','paid','shipped','FX7712009','FedEx','USD',now() - interval '9 days'),
('VS-24083','{"name":"Kofi Anane","email":"kofi@example.com","phone":"+233 24 555 1212","address":"12 Ridge Road","city":"Accra","postalCode":"GA-023","country":"Ghana"}','[{"productId":"","name":"Terracotta Sunburst Fan","price":68,"quantity":3,"image":"/__l5e/assets-v1/79683c8d-0da3-4ebf-88bd-cea7436f1f02/product-fan.jpg"}]',204,0,10.20,214.20,'mobile_money','paid','processing',NULL,'Ghana Post','GHS',now() - interval '4 days'),
('VS-24084','{"name":"Priya Nair","email":"priya@example.com","phone":"+1 415 555 0198","address":"88 Dolores St","city":"San Francisco","postalCode":"94110","country":"United States"}','[{"productId":"","name":"Golden Check Market Tote","price":132,"quantity":1,"image":"/__l5e/assets-v1/80686690-31c5-4272-b939-6b9c46601886/tote.jpg"},{"productId":"","name":"Indigo Ray Fan","price":46,"quantity":1,"image":"/__l5e/assets-v1/79683c8d-0da3-4ebf-88bd-cea7436f1f02/product-fan.jpg"}]',178,12,8.90,198.90,'card','pending','unfulfilled',NULL,NULL,'USD',now() - interval '2 days'),
('VS-24085','{"name":"Tomas Reuter","email":"tomas@example.com","phone":"+49 30 1234567","address":"Oderberger Str 9","city":"Berlin","postalCode":"10435","country":"Germany"}','[{"productId":"","name":"Zebra Fringe Sculpture Basket","price":198,"quantity":1,"image":"/__l5e/assets-v1/c9b30099-29a0-4b71-864e-c7f30d51aae5/bolga-hero.jpg"}]',198,0,9.90,207.90,'card','paid','unfulfilled',NULL,NULL,'EUR',now() - interval '10 hours');

INSERT INTO public.journal (title, slug, excerpt, content, cover_image, author, read_time, published_at, tags) VALUES
('How a Bolga basket is born','how-a-bolga-basket-is-born','From the harmattan harvest of veta vera grass to the leather-bound rim, a basket passes through five sets of hands.','Elephant grass — veta vera — is cut at the end of the rainy season, split by thumbnail, twisted into cord and left to dry in the sun. Dye pots are set with roots, bark and indigo, and the cord is dipped in batches so each colour carries the season it was made in.

Weaving begins at the base, flat on the knee. There is no mould and no drawing; the pattern is counted in the weaver''s head. A large sculptural piece takes eight to twelve days. The rim is finished by a leather worker in Bolgatanga market, stitching with waxed thread.

Baskets are folded flat for the journey. A mist of warm water and ten minutes of patient shaping brings them back to full form — this is the last step of the weave, and you perform it yourself.','/__l5e/assets-v1/3f1fce51-4358-4890-98cf-4a51f4535186/artisan.jpg','Vetastudio',6,now() - interval '12 days',ARRAY['craft','process']),
('Reshaping a folded basket','reshaping-a-folded-basket','Your basket travels flat. Here is the ten-minute ritual that returns it to shape.','Fill a spray bottle with warm water. Mist the outside of the basket until the grass darkens slightly — damp, never soaked. Work the walls outward with both hands, pressing from the inside, turning as you go.

Stuff the basket loosely with towels or paper to hold the volume and leave it overnight away from direct sun and radiators. In the morning remove the filling; the grass will have dried into its new memory.

Repeat once or twice a year, or any time the shape softens.','/__l5e/assets-v1/c9b30099-29a0-4b71-864e-c7f30d51aae5/bolga-hero.jpg','Vetastudio',4,now() - interval '30 days',ARRAY['care','guide']),
('Fair wages in the weaving cooperatives','fair-wages-in-the-weaving-cooperatives','What fair-trade certification actually changes in a Sumbrungu weaving household.','A fair price for a basket is not one number. It is the grass, the dye, the days, and the leather — and then the difference between a middleman''s price and a cooperative price, which is usually the school fees.

Vetastudio buys directly from three cooperatives around Bolgatanga and publishes the per-piece rate paid to the weaver. Payment is made at collection, not on sale, so the risk sits with us rather than with the household.','/__l5e/assets-v1/3f1fce51-4358-4890-98cf-4a51f4535186/artisan.jpg','Vetastudio',5,now() - interval '45 days',ARRAY['transparency','artisans']);

INSERT INTO public.store_settings (id, currency_rates, tax_rate, shipping_domestic, shipping_international, free_shipping_threshold, announcement, support_email, support_phone) VALUES
('default','{"USD":1,"EUR":0.92,"GBP":0.79,"GHS":15.4,"CAD":1.36}',0.05,12,28,150,'Free worldwide shipping on orders over $150 — every basket woven by hand in Bolgatanga','care@vetastudio.com','+233 20 411 8802');

INSERT INTO public.cms_homepage (id, hero_slides, value_pillars, weaver_spotlights, process_steps, campaign_cards) VALUES
('default',
'[{"title":"Woven wild in Bolgatanga","subtitle":"Sculptural elephant grass baskets, made by hand and left unfinished where the weaver wanted it wild.","image":"/__l5e/assets-v1/c9b30099-29a0-4b71-864e-c7f30d51aae5/bolga-hero.jpg","badge":"2026 Harvest Collection","ctaLabel":"Shop Collection","ctaHref":"/shop"},{"title":"Light, filtered through grass","subtitle":"Hand-coiled pendant shades in root-dyed ochre and indigo.","image":"/__l5e/assets-v1/4d820abd-023e-46e1-b068-2d5ba0f1ed77/product-lampshade.jpg","badge":"New Lighting","ctaLabel":"Shop Lampshades","ctaHref":"/shop"}]',
'[{"title":"100% Veta Vera Grass","body":"Rain-fed, hand-cut, never synthetic."},{"title":"Fair-Wage Certified","body":"Per-piece rates published, paid at collection."},{"title":"Carbon-Neutral Shipping","body":"Every parcel offset at source."},{"title":"Free Reshaping Guide","body":"Ten minutes and a spray bottle."}]',
'[{"name":"Ayamga Atinga","village":"Sumbrungu","years":22,"quote":"I leave the ends wild so you can see my hand in it.","image":"/__l5e/assets-v1/3f1fce51-4358-4890-98cf-4a51f4535186/artisan.jpg"},{"name":"Azuma Awini","village":"Zuarungu","years":15,"quote":"The pattern lives in my head, never on paper.","image":"/__l5e/assets-v1/3f1fce51-4358-4890-98cf-4a51f4535186/artisan.jpg"}]',
'[{"step":"Harvesting","body":"Veta vera grass cut at the close of the rains, split by thumbnail and sun-dried."},{"step":"Dyeing","body":"Roots, bark and indigo simmered in shared pots; cord dipped in batches."},{"step":"Weaving","body":"Started flat on the knee, counted from memory. Eight to twelve days for a large piece."},{"step":"Leather Trimming","body":"Rims and handles stitched with waxed thread in Bolgatanga market."},{"step":"Reshaping","body":"Folded for travel, misted and shaped by you at home."}]',
'[{"title":"Sale: Collector Sculptures","body":"Up to 20% off selected fringe pieces.","href":"/shop","image":"/__l5e/assets-v1/a81bddfd-e0c5-4410-b161-26cb04573b5a/product-sculpture.jpg"},{"title":"The Storage Edit","body":"Deep baskets with double leather handles.","href":"/shop","image":"/__l5e/assets-v1/f9dcf4cf-248f-49c2-87cd-ea4e34f43ff8/product-storage.jpg"}]');